# Site settings
title: Mikebdict
description: >-
  Mikeb's Linux & Python page
lang: en-GB
timezone: Europe/London
image: assets/img/404.jpg # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/mikebdict/mikebdict.github.io
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: MikeB
  bio: >-
    YAGP - Yet another Github page that chronicles my preperation for LPIC, learning python and other things I'm trying to 'do somewhat properly' for the first time.
  username: mikebdict
  email: mike.bland.dict@gmail.com
  avatar: /assets/img/mikebraven.jpg

# Url settings
url: "https://mikebdict.github.io"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
